name: Generate version.json from pyproject.toml

on:
  push:
    paths:
      - 'pyproject.toml'
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install toml module
        run: pip install toml

      - name: Extract version from pyproject.toml
        run: |
          python -c "
import toml
with open('pyproject.toml', 'r') as f:
    data = toml.load(f)
version = data.get('project', {}).get('version', 'unknown')
with open('version.json', 'w') as out:
    out.write('{\"version\": \"%s\"}' % version)
"

      - name: Commit version.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add version.json
          git commit -m 'Update version.json' || echo 'No changes to commit'
          git push
